# Generated by Django 6.1 on 2026-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_adminprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblemodel',
            name='property_type',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Local Comercial', 'Local Comercial'), ('Terreno', 'Terreno'), ('Finca', 'Finca')], max_length=30),
        ),
    ]
