# Generated by Django 6.0.7 on 2026-08-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaquillajeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Labial', 'Labial'), ('Base', 'Base'), ('Rubor', 'Rubor'), ('Sombra', 'Sombra'), ('Máscara de pestañas', 'Máscara de pestañas')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'maquillaje_maquillaje',
                'ordering': ['-creado_en'],
            },
        ),
    ]
